# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
julia:
  - 1.2
branches:
  only:
    - master
addons:
  apt:
    packages:
      - xvfb
      - xauth
      - libgconf-2-4
      - libgtk-3-dev
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - xvfb-run julia -e 'using Pkg; ENV["PYTHON"]=""; Pkg.build(); Pkg.test(coverage=true)'
notifications:
  email: false
