# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
codecov: true
coveralls: true
branches:
  only:
    - master
notifications:
  email: true
