# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - osx
  - windows
julia:
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia:
      - 1.1
      - nightly
codecov: true
coveralls: true
branches:
  only: master
addons:
  apt:
    packages: libgtk-3-dev
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; ENV["PYTHON"]=""; Pkg.build(); Pkg.test(coverage=true)' ## Re-configure Python environment for PyCall to use Julia-specific Python version via Conda.jl package
notifications:
  email: true
